/** Shared between the export dialog (client, for checkbox labels) and the export API route
 *  (server, for the actual cell values) — keeps the column list in one place. */
export interface ExportColumnDef {
  id: string;
  label: string;
  defaultOn: boolean;
}

// the curated, frequently-used set — checked by default so a normal export stays a manageable
// handful of columns instead of the entire record.
const CORE_COLUMNS: ExportColumnDef[] = [
  { id: 'organisation', label: 'organisation', defaultOn: true },
  { id: 'registrationType', label: 'registration type', defaultOn: true },
  { id: 'pocName', label: 'poc name', defaultOn: true },
  { id: 'email', label: 'email', defaultOn: true },
  { id: 'phone', label: 'phone', defaultOn: true },
  { id: 'website', label: 'website', defaultOn: false },
  { id: 'linkedin', label: 'linkedin', defaultOn: false },
  { id: 'founders', label: 'founders', defaultOn: false },
  { id: 'reviewStatus', label: 'review status', defaultOn: true },
  { id: 'decisionStatus', label: 'decision status', defaultOn: true },
  { id: 'operatingModel', label: 'operating model', defaultOn: true },
  { id: 'states', label: 'states', defaultOn: true },
  { id: 'annualBudget', label: 'annual operating budget', defaultOn: false },
  { id: 'yearsExperience', label: 'years experience', defaultOn: false },
  { id: 'eligibility', label: 'eligibility', defaultOn: true },
  { id: 'eligibilityIssues', label: 'eligibility issues', defaultOn: true },
  { id: 'humanComposite', label: 'human score', defaultOn: true },
  { id: 'aiComposite', label: 'AI composite', defaultOn: false },
  { id: 'reviewer', label: 'reviewer', defaultOn: true },
  { id: 'submittedAt', label: 'submitted at', defaultOn: true },
  { id: 'comments', label: 'comments', defaultOn: false },
];

// every other field the applicant actually filled in on the form (plus a few relation-derived
// summaries) — off by default, but selectable one at a time or all together via "select all" in
// the export dialog, so a full Zoho-style record dump is one click away without cluttering the
// default export.
const FULL_DUMP_COLUMNS: ExportColumnDef[] = [
  { id: 'pocFirstName', label: 'poc first name', defaultOn: false },
  { id: 'pocLastName', label: 'poc last name', defaultOn: false },
  { id: 'designation', label: 'designation', defaultOn: false },
  { id: 'incorporationDate', label: 'incorporated', defaultOn: false },
  { id: 'location', label: 'location', defaultOn: false },
  { id: 'orgType', label: 'organisation type', defaultOn: false },
  { id: 'stageRaw', label: 'current stage (self-reported)', defaultOn: false },
  { id: 'stageNormalized', label: 'current stage (normalised)', defaultOn: false },
  { id: 'problemAddressing', label: 'problem addressing', defaultOn: false },
  { id: 'valueChainFocus', label: 'value chain focus', defaultOn: false },
  { id: 'beneficiaries', label: 'beneficiaries', defaultOn: false },
  { id: 'smallMarginalFarmerPct', label: 'small/marginal farmer %', defaultOn: false },
  { id: 'areaHectaresRaw', label: 'area under coverage', defaultOn: false },
  { id: 'aboutSolution', label: 'about the solution', defaultOn: false },
  { id: 'solutionCategory', label: 'solution category', defaultOn: false },
  { id: 'trl', label: 'TRL', defaultOn: false },
  { id: 'waterEfficiencyFocus', label: 'water efficiency focus', defaultOn: false },
  { id: 'waterEfficiencyEstimate', label: 'water efficiency estimate', defaultOn: false },
  { id: 'cropProductionFocus', label: 'crop production focus', defaultOn: false },
  { id: 'focusCrops', label: 'focus crops', defaultOn: false },
  { id: 'teamSize', label: 'team size', defaultOn: false },
  { id: 'founderEmails', label: 'founder emails', defaultOn: false },
  { id: 'founderLinkedins', label: 'founder LinkedIns', defaultOn: false },
  { id: 'pitchDeckUrl', label: 'pitch deck url', defaultOn: false },
  { id: 'legalRegistrationType', label: 'legal registration type (raw)', defaultOn: false },
  { id: 'fcraStatus', label: 'FCRA registration', defaultOn: false },
  { id: 'cert12A', label: '12A certificate', defaultOn: false },
  { id: 'cert80G', label: '80G certificate', defaultOn: false },
  { id: 'csr1Registration', label: 'CSR-1 registration', defaultOn: false },
  { id: 'darpanRegistered', label: 'NITI Aayog DARPAN ID', defaultOn: false },
  { id: 'darpanIdNumber', label: 'DARPAN registration number', defaultOn: false },
  { id: 'funders', label: 'funders', defaultOn: false },
  { id: 'operatingModelArchetype', label: 'operating model archetype', defaultOn: false },
  { id: 'operatingModelSecondary', label: 'operating model (secondary)', defaultOn: false },
  { id: 'operatingModelDescription', label: 'how it works in practice', defaultOn: false },
  { id: 'primaryCrops', label: 'primary crops', defaultOn: false },
  { id: 'regenerativePractices', label: 'regenerative practices', defaultOn: false },
  { id: 'adoptionHurdle', label: 'biggest adoption hurdle', defaultOn: false },
  { id: 'techTools', label: 'tools used', defaultOn: false },
  { id: 'techToolsInternal', label: 'tools developed internally', defaultOn: false },
  { id: 'techUseCases', label: 'top tech use cases', defaultOn: false },
  { id: 'otherTools', label: 'other tools', defaultOn: false },
  { id: 'verifiedImpacts', label: 'verified impacts', defaultOn: false },
  { id: 'statesOperating', label: 'states of operation (raw)', defaultOn: false },
  { id: 'farmersCount', label: 'farmers reached', defaultOn: false },
  { id: 'smallholderFarmersCount', label: 'smallholder farmers (≤2ha)', defaultOn: false },
  { id: 'avgLandHolding', label: 'average land holding (ha)', defaultOn: false },
  { id: 'areaUnderRegenPractice', label: 'area under regenerative practice (ha)', defaultOn: false },
  { id: 'villagesCount', label: 'villages count', defaultOn: false },
  { id: 'districtsCount', label: 'districts count', defaultOn: false },
  { id: 'villagesDistrictsRaw', label: 'villages/districts (raw)', defaultOn: false },
  { id: 'worksBeyondAg', label: 'works beyond agriculture', defaultOn: false },
  { id: 'materialsInLocalLanguages', label: 'materials in local languages', defaultOn: false },
  { id: 'teamFormalTraining', label: 'team formally trained', defaultOn: false },
  { id: 'teamTrainingDescription', label: 'team training details', defaultOn: false },
  { id: 'melHandling', label: 'MEL handled', defaultOn: false },
  { id: 'fundUsagePlan', label: 'planned use of prize funds', defaultOn: false },
  { id: 'reportLinks', label: 'published reports / case studies', defaultOn: false },
  { id: 'otherDevelopmentAreas', label: 'other development work', defaultOn: false },
  { id: 'heardAboutChallenge', label: 'how they heard about the challenge', defaultOn: false },
  { id: 'otherHeardAbout', label: 'how they heard (other)', defaultOn: false },
  { id: 'infoAccurateConfirmed', label: 'info confirmed accurate by applicant', defaultOn: false },
  { id: 'enrichmentSummary', label: 'public-data enrichment summary', defaultOn: false },
  { id: 'enrichmentSource', label: 'enrichment source', defaultOn: false },
  { id: 'opModelVerdict', label: 'org validation verdict', defaultOn: false },
  { id: 'opModelSummary', label: 'org validation summary', defaultOn: false },
  { id: 'fundersVerdict', label: 'funders check verdict', defaultOn: false },
  { id: 'fundersSummary', label: 'funders check summary', defaultOn: false },
  { id: 'founderVerdict', label: 'founder expertise verdict', defaultOn: false },
  { id: 'founderSummary', label: 'founder expertise summary', defaultOn: false },
  { id: 'stageStatus', label: 'pipeline stage', defaultOn: false },
  { id: 'bench', label: 'jury bench', defaultOn: false },
  { id: 'source', label: 'source', defaultOn: false },
  { id: 'historicallyShortlisted', label: 'historically shortlisted (AgWater 2024)', defaultOn: false },
  { id: 'targetMatch', label: 'target wishlist match', defaultOn: false },
  { id: 'createdAt', label: 'created at', defaultOn: false },
  { id: 'updatedAt', label: 'last updated at', defaultOn: false },
];

export const EXPORT_COLUMNS: ExportColumnDef[] = [...CORE_COLUMNS, ...FULL_DUMP_COLUMNS];
